---
name: janeway

# CAREFUL with this env file, Docker env files don't support interpolation!
env_file:
  - dockerfiles/lando_defaults.env
  - dockerfiles/lando_local.env

services:
  appserver:
    type: python:3.8
    command: python3 /app/src/manage.py runserver 0.0.0.0:8000 -v 3
    build_as_root:
      # - sed -i~orig -e 's/Typesi(.) deb/Types$1 deb-src/' /etc/apt/sources.list.d/debian.sources && cat /etc/apt/sources.list.d/debian.sources~orig >> /etc/apt/sources.list.d/debian.sources && apt-get update -qq && apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev libjpeg-dev && apt-get build-dep -y lxml
      - "sed -i -e 's/Types: deb/Types: deb-src/' /etc/apt/sources.list.d/debian.sources && apt-get update -qq && apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev libjpeg-dev"
    build:
       - cd /app && pip3 install --upgrade pip && pip3 install Cython && pip3 install -r requirements.txt &&  pip3 install -r dev-requirements.txt && pip3 install psycopg2
    scanner: true
    overrides:
      ports:
        - '8000:8000'
      environment:
        PYTHONPATH: "/app/src"
        JANEWAY_SETTINGS_MODULE: "core.settings" # this is the path to the Janeway settings file, which is in src/core/settings.py
    moreHttpPorts:
      - '8000'
  db:
    type: postgres:10
    portforward: true
    creds:
      user: postgres
      password: 
      database: janeway

tooling:
  python3:
    service: appserver
    cmd: python3
    dir: /app/src
  pip3:
    service: appserver
    description: run pip3 commands to manage Python package installation in this environment
    cmd: pip3
    dir: /app/src
  manage:
    service: appserver
    cmd: python3 manage.py
    dir: /app/src
  restart-runserver:
    service: appserver
    description: Quickly restarts the Django runserver process, follows logs, and enables interactive debugging
    cmd: killall python || python3 /app/src/manage.py runserver 0.0.0.0:8000 -v 3
    dir: /app/src
    user: root
  psql:
    service: db
    cmd: psql -U postgres
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: db
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
