# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 21:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0022_merge_20190411_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='password_length',
            field=models.PositiveIntegerField(default=6, help_text='The minimum length of an account password.', validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
