# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-06 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0034_merge_20190411_1321'),
        ('submission', '0034_auto_20190416_1009'),
    ]

    operations = [
    ]
