# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0038_merge_20190812_1614'),
        ('submission', '0035_merge_20190806_1123'),
    ]

    operations = [
    ]
