# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0039_merge_20200108_1303'),
        ('submission', '0039_auto_20191115_1253'),
    ]

    operations = [
    ]
